import "../assets/fontawesome-webfont.eot";
import "../assets/fontawesome-webfont.svg";
import "../assets/fontawesome-webfont.ttf";
import "../assets/fontawesome-webfont.woff";
import "../assets/fontawesome-webfont.woff2";
import "../assets/fontAwesome";
import "../assets/font-awesome";
import "../assets/loader";
import "file-loader?name=[name].[ext]!./lib/pouchdb";