"""removed roleId

Revision ID: 08dc11029540
Revises: cd454cecb6e8
Create Date: 2017-04-27 00:52:42.405784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08dc11029540'
down_revision = 'cd454cecb6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_authorId_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['authorId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('roles_users_role_id_fkey', 'roles_users', type_='foreignkey')
    op.drop_constraint('roles_users_user_id_fkey', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('user_roleId_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'roleId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roleId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_roleId_fkey', 'user', 'role', ['roleId'], ['id'])
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.create_foreign_key('roles_users_user_id_fkey', 'roles_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key('roles_users_role_id_fkey', 'roles_users', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'course', schema='public', type_='foreignkey')
    op.create_foreign_key('course_authorId_fkey', 'course', 'user', ['authorId'], ['id'])
    # ### end Alembic commands ###
