"""Added course tags

Revision ID: 495aae05274a
Revises: fb8766db16ac
Create Date: 2017-05-28 17:31:23.016586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495aae05274a'
down_revision = 'fb8766db16ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tags_courses',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['public.course.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['public.tag.id'], ),
    schema='public'
    )
    op.drop_constraint('course_authorId_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['authorId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('preface_image_courseId_fkey', 'preface_image', type_='foreignkey')
    op.create_foreign_key(None, 'preface_image', 'course', ['courseId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('roles_users_user_id_fkey', 'roles_users', type_='foreignkey')
    op.drop_constraint('roles_users_role_id_fkey', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.create_foreign_key('roles_users_role_id_fkey', 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key('roles_users_user_id_fkey', 'roles_users', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'preface_image', schema='public', type_='foreignkey')
    op.create_foreign_key('preface_image_courseId_fkey', 'preface_image', 'course', ['courseId'], ['id'])
    op.drop_constraint(None, 'course', schema='public', type_='foreignkey')
    op.create_foreign_key('course_authorId_fkey', 'course', 'user', ['authorId'], ['id'])
    op.drop_table('tags_courses', schema='public')
    op.drop_table('tag', schema='public')
    # ### end Alembic commands ###
