"""Changed course id from 32 to 16

Revision ID: 61575dea0c4a
Revises: b4d25cd694da
Create Date: 2017-06-09 14:19:47.051311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61575dea0c4a'
down_revision = 'b4d25cd694da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_authorId_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['authorId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('preface_image_courseId_fkey', 'preface_image', type_='foreignkey')
    op.create_foreign_key(None, 'preface_image', 'course', ['courseId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('roles_users_user_id_fkey', 'roles_users', type_='foreignkey')
    op.drop_constraint('roles_users_role_id_fkey', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('tags_courses_tag_id_fkey', 'tags_courses', type_='foreignkey')
    op.drop_constraint('tags_courses_course_id_fkey', 'tags_courses', type_='foreignkey')
    op.create_foreign_key(None, 'tags_courses', 'tag', ['tag_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_courses', 'course', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tags_courses', schema='public', type_='foreignkey')
    op.create_foreign_key('tags_courses_course_id_fkey', 'tags_courses', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tags_courses_tag_id_fkey', 'tags_courses', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.create_foreign_key('roles_users_role_id_fkey', 'roles_users', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('roles_users_user_id_fkey', 'roles_users', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'preface_image', schema='public', type_='foreignkey')
    op.create_foreign_key('preface_image_courseId_fkey', 'preface_image', 'course', ['courseId'], ['id'])
    op.drop_constraint(None, 'course', schema='public', type_='foreignkey')
    op.create_foreign_key('course_authorId_fkey', 'course', 'user', ['authorId'], ['id'])
    # ### end Alembic commands ###
