"""users and roles

Revision ID: 71a34a7b5930
Revises: b3f90880efe1
Create Date: 2017-04-21 10:48:49.538761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a34a7b5930'
down_revision = 'b3f90880efe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('RoleId'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Users',
    sa.Column('UserId', sa.String(length=32), nullable=False),
    sa.Column('Name', sa.String(length=40), nullable=True),
    sa.Column('Surname', sa.String(length=40), nullable=True),
    sa.Column('LastName', sa.String(length=40), nullable=True),
    sa.Column('RoleId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RoleId'], ['Roles.RoleId'], ),
    sa.PrimaryKeyConstraint('UserId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Roles')
    # ### end Alembic commands ###
