"""Course contents removed

Revision ID: 7994ed91877b
Revises: 4009be37e439
Create Date: 2017-06-13 10:27:42.381643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7994ed91877b'
down_revision = '4009be37e439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chapter_courseId_fkey', 'chapter', type_='foreignkey')
    op.create_foreign_key(None, 'chapter', 'course', ['courseId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('chapter_file_chapterId_fkey', 'chapter_file', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_file', 'chapter', ['chapterId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('chapter_image_chapterId_fkey', 'chapter_image', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_image', 'chapter', ['chapterId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('course_authorId_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['authorId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('course', 'contents')
    op.drop_constraint('preface_image_courseId_fkey', 'preface_image', type_='foreignkey')
    op.create_foreign_key(None, 'preface_image', 'course', ['courseId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('roles_users_role_id_fkey', 'roles_users', type_='foreignkey')
    op.drop_constraint('roles_users_user_id_fkey', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('tags_courses_tag_id_fkey', 'tags_courses', type_='foreignkey')
    op.drop_constraint('tags_courses_course_id_fkey', 'tags_courses', type_='foreignkey')
    op.create_foreign_key(None, 'tags_courses', 'tag', ['tag_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_courses', 'course', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tags_courses', schema='public', type_='foreignkey')
    op.create_foreign_key('tags_courses_course_id_fkey', 'tags_courses', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tags_courses_tag_id_fkey', 'tags_courses', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.create_foreign_key('roles_users_user_id_fkey', 'roles_users', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('roles_users_role_id_fkey', 'roles_users', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'preface_image', schema='public', type_='foreignkey')
    op.create_foreign_key('preface_image_courseId_fkey', 'preface_image', 'course', ['courseId'], ['id'])
    op.add_column('course', sa.Column('contents', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course', schema='public', type_='foreignkey')
    op.create_foreign_key('course_authorId_fkey', 'course', 'user', ['authorId'], ['id'])
    op.drop_constraint(None, 'chapter_image', schema='public', type_='foreignkey')
    op.create_foreign_key('chapter_image_chapterId_fkey', 'chapter_image', 'chapter', ['chapterId'], ['id'])
    op.drop_constraint(None, 'chapter_file', schema='public', type_='foreignkey')
    op.create_foreign_key('chapter_file_chapterId_fkey', 'chapter_file', 'chapter', ['chapterId'], ['id'])
    op.drop_constraint(None, 'chapter', schema='public', type_='foreignkey')
    op.create_foreign_key('chapter_courseId_fkey', 'chapter', 'course', ['courseId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
