"""created storage

Revision ID: 8477e43f5c6f
Revises: 71a34a7b5930
Create Date: 2017-04-21 19:50:10.316568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8477e43f5c6f'
down_revision = '71a34a7b5930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CourseStatuses',
    sa.Column('CourseStatusId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('CourseStatusId')
    )
    op.create_table('Tags',
    sa.Column('TagId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('TagId')
    )
    op.create_table('Courses',
    sa.Column('CourseId', sa.String(length=32), nullable=False),
    sa.Column('Name', sa.String(length=200), nullable=False),
    sa.Column('Contents', sa.Text(), nullable=False),
    sa.Column('Preface', sa.Text(), nullable=False),
    sa.Column('AuthorId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['AuthorId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('CourseId')
    )
    op.create_table('CourseChapters',
    sa.Column('CourseChapterId', sa.String(length=32), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('Images', sa.Boolean(), nullable=False),
    sa.Column('CourseId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['CourseId'], ['Courses.CourseId'], ),
    sa.PrimaryKeyConstraint('CourseChapterId')
    )
    op.create_table('CourseTests',
    sa.Column('CourseTestId', sa.String(length=32), nullable=False),
    sa.Column('Questions', sa.Text(), nullable=False),
    sa.Column('Images', sa.Boolean(), nullable=False),
    sa.Column('Files', sa.Boolean(), nullable=False),
    sa.Column('CourseId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['CourseId'], ['Courses.CourseId'], ),
    sa.PrimaryKeyConstraint('CourseTestId')
    )
    op.create_table('CoursesTagsXRef',
    sa.Column('CourseId', sa.String(length=32), nullable=False),
    sa.Column('TagId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CourseId'], ['Courses.CourseId'], ),
    sa.ForeignKeyConstraint(['TagId'], ['Tags.TagId'], ),
    sa.PrimaryKeyConstraint('CourseId', 'TagId')
    )
    op.create_table('UsersCoursesStatus',
    sa.Column('UserId', sa.String(length=32), nullable=False),
    sa.Column('CourseId', sa.String(length=32), nullable=False),
    sa.Column('StatusId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CourseId'], ['Courses.CourseId'], ),
    sa.ForeignKeyConstraint(['StatusId'], ['CourseStatuses.CourseStatusId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('UserId', 'CourseId')
    )
    op.create_table('CourseAnswers',
    sa.Column('CourseAnswerId', sa.String(length=32), nullable=False),
    sa.Column('AnswerKeys', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['CourseAnswerId'], ['CourseTests.CourseTestId'], ),
    sa.PrimaryKeyConstraint('CourseAnswerId')
    )
    op.create_table('CourseChapterComments',
    sa.Column('CourseChapterCommentId', sa.BigInteger(), nullable=False),
    sa.Column('Contents', sa.Text(), nullable=False),
    sa.Column('Images', sa.Boolean(), nullable=False),
    sa.Column('UserId', sa.String(length=32), nullable=False),
    sa.Column('CourseChapterId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['CourseChapterId'], ['CourseChapters.CourseChapterId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('CourseChapterCommentId')
    )
    op.create_table('CourseChapterFiles',
    sa.Column('CourseChapterFileId', sa.String(length=32), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('CourseChapterId', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['CourseChapterId'], ['CourseChapters.CourseChapterId'], ),
    sa.PrimaryKeyConstraint('CourseChapterFileId')
    )
    op.create_table('CourseChapterImages',
    sa.Column('CourseChapterImageId', sa.String(length=32), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('CourseChapterId', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['CourseChapterId'], ['CourseChapters.CourseChapterId'], ),
    sa.PrimaryKeyConstraint('CourseChapterImageId')
    )
    op.create_table('CourseTestFiles',
    sa.Column('CourseTestFileId', sa.String(length=32), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('CourseTestId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['CourseTestId'], ['CourseTests.CourseTestId'], ),
    sa.PrimaryKeyConstraint('CourseTestFileId')
    )
    op.create_table('CourseTestImages',
    sa.Column('CourseTestImageId', sa.String(length=32), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('CourseTestId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['CourseTestId'], ['CourseTests.CourseTestId'], ),
    sa.PrimaryKeyConstraint('CourseTestImageId')
    )
    op.create_table('UserChapterRead',
    sa.Column('UserId', sa.String(length=32), nullable=False),
    sa.Column('CourseChapterId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['CourseChapterId'], ['CourseChapters.CourseChapterId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('UserId', 'CourseChapterId')
    )
    op.create_table('UsersCourseTest',
    sa.Column('UserId', sa.String(length=32), nullable=False),
    sa.Column('CourseTestId', sa.String(length=32), nullable=False),
    sa.Column('Mark', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CourseTestId'], ['CourseTests.CourseTestId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('UserId', 'CourseTestId')
    )
    op.create_table('CourseChapterCommentImages',
    sa.Column('CourseChapterCommentImageId', sa.String(length=32), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('CourseChapterCommentId', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['CourseChapterCommentId'], ['CourseChapterComments.CourseChapterCommentId'], ),
    sa.PrimaryKeyConstraint('CourseChapterCommentImageId')
    )
    op.alter_column('Roles', 'Name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('Users', 'LastName',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('Users', 'Name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('Users', 'RoleId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Users', 'Surname',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'Surname',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('Users', 'RoleId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Users', 'Name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('Users', 'LastName',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('Roles', 'Name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_table('CourseChapterCommentImages')
    op.drop_table('UsersCourseTest')
    op.drop_table('UserChapterRead')
    op.drop_table('CourseTestImages')
    op.drop_table('CourseTestFiles')
    op.drop_table('CourseChapterImages')
    op.drop_table('CourseChapterFiles')
    op.drop_table('CourseChapterComments')
    op.drop_table('CourseAnswers')
    op.drop_table('UsersCoursesStatus')
    op.drop_table('CoursesTagsXRef')
    op.drop_table('CourseTests')
    op.drop_table('CourseChapters')
    op.drop_table('Courses')
    op.drop_table('Tags')
    op.drop_table('CourseStatuses')
    # ### end Alembic commands ###
