"""Removed role description

Revision ID: e51e36b52678
Revises: 98a0b99d24c5
Create Date: 2017-06-15 10:21:05.738142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51e36b52678'
down_revision = '98a0b99d24c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chapter_courseId_fkey', 'chapter', type_='foreignkey')
    op.create_foreign_key(None, 'chapter', 'course', ['courseId'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('chapter_file_chapterId_fkey', 'chapter_file', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_file', 'chapter', ['chapterId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('course_authorId_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['authorId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('image_courseId_fkey', 'image', type_='foreignkey')
    op.drop_constraint('image_chapterId_fkey', 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'course', ['courseId'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'image', 'chapter', ['chapterId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('role', 'description')
    op.drop_constraint('roles_users_role_id_fkey', 'roles_users', type_='foreignkey')
    op.drop_constraint('roles_users_user_id_fkey', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('tags_courses_tag_id_fkey', 'tags_courses', type_='foreignkey')
    op.drop_constraint('tags_courses_course_id_fkey', 'tags_courses', type_='foreignkey')
    op.create_foreign_key(None, 'tags_courses', 'tag', ['tag_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_courses', 'course', ['course_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tags_courses', schema='public', type_='foreignkey')
    op.create_foreign_key('tags_courses_course_id_fkey', 'tags_courses', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tags_courses_tag_id_fkey', 'tags_courses', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.create_foreign_key('roles_users_user_id_fkey', 'roles_users', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('roles_users_role_id_fkey', 'roles_users', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('role', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'image', schema='public', type_='foreignkey')
    op.create_foreign_key('image_chapterId_fkey', 'image', 'chapter', ['chapterId'], ['id'])
    op.create_foreign_key('image_courseId_fkey', 'image', 'course', ['courseId'], ['id'])
    op.drop_constraint(None, 'course', schema='public', type_='foreignkey')
    op.create_foreign_key('course_authorId_fkey', 'course', 'user', ['authorId'], ['id'])
    op.drop_constraint(None, 'chapter_file', schema='public', type_='foreignkey')
    op.create_foreign_key('chapter_file_chapterId_fkey', 'chapter_file', 'chapter', ['chapterId'], ['id'])
    op.drop_constraint(None, 'chapter', schema='public', type_='foreignkey')
    op.create_foreign_key('chapter_courseId_fkey', 'chapter', 'course', ['courseId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
