"""added time for courses and comments

Revision ID: f7a9b1807326
Revises: 8477e43f5c6f
Create Date: 2017-04-24 07:30:11.982269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a9b1807326'
down_revision = '8477e43f5c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CourseChapterComments', sa.Column('PostTime', sa.DateTime(), nullable=False))
    op.add_column('CourseChapters', sa.Column('Files', sa.Boolean(), nullable=False))
    op.add_column('Courses', sa.Column('PostTime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Courses', 'PostTime')
    op.drop_column('CourseChapters', 'Files')
    op.drop_column('CourseChapterComments', 'PostTime')
    # ### end Alembic commands ###
