"""course preface and images added

Revision ID: fb8766db16ac
Revises: 08dc11029540
Create Date: 2017-04-28 18:20:29.194389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8766db16ac'
down_revision = '08dc11029540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preface_image',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('courseId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['public.course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.add_column('course', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('course', sa.Column('icon', sa.String(length=200), nullable=True))
    op.add_column('course', sa.Column('rev', sa.Integer(), nullable=False))
    op.drop_constraint('course_authorId_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['authorId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('roles_users_user_id_fkey', 'roles_users', type_='foreignkey')
    op.drop_constraint('roles_users_role_id_fkey', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', schema='public', type_='foreignkey')
    op.create_foreign_key('roles_users_role_id_fkey', 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key('roles_users_user_id_fkey', 'roles_users', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'course', schema='public', type_='foreignkey')
    op.create_foreign_key('course_authorId_fkey', 'course', 'user', ['authorId'], ['id'])
    op.drop_column('course', 'rev')
    op.drop_column('course', 'icon')
    op.drop_column('course', 'description')
    op.drop_table('preface_image', schema='public')
    # ### end Alembic commands ###
